name: Build

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

# We dont have tests yet, so we can just build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt install -y --fix-missing --no-install-recommends git build-essential software-properties-common cmake libtbb-dev libboost-system-dev libboost-serialization-dev libpdal-dev libeigen3-dev
      - name: Build
        run: mkdir build && cd build && cmake -DWITH_GBT=ON -DPORTABLE_BUILD=ON .. && make -j$(nproc)
      - name: Archive compiled binaries
        run: cd build && tar -czvf opc.tar.gz pcclassify pctrain
      - name: Upload Distribution Files
        uses: actions/upload-artifact@v2
        with:
          name: Compiled Binaries
          path: build/opc.tar.gz
      - name: Upload Binaries to Release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/opc.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
